src/main/resources/logbook/gui/main.fxml

以下のショートカットキーを追加しました．改でない航海日誌についていたものと，設定画面を開くものです．
- 戦闘ログ(出撃統計)
- ^A
- 所有装備
- ^I
- 所有艦娘
- ^S
- お風呂に入りたい艦娘
- ^N
- 経験値計算機
- ^C

サブウィンドウを開くときのショートカットキー

---

src/main/java/logbook/internal/ConfigReader.java

https://github.com/sanaehirotaka/logbook-kai/issues/22
ArrayIndexOutOfBoundsExceptionをキャッチするように修正しました。
破損したXMLファイルが存在する状態で起動し、遠征時間等が表示されることを確認しました。

fix: 設定ファイル破損時に正常起動しない #22

---

src/main/java/logbook/bean/AppConfig.java
src/main/java/logbook/internal/gui/TableTool.java
src/main/java/logbook/internal/gui/Tools.java
src/main/resources/logbook/gui/require_ndock.fxml
src/main/resources/logbook/gui/ship_table.fxml

Issue #32 に一部関連して、所有艦娘とお風呂に入りたい艦娘のテーブルのソート順を保存する変更をつくってみました。また PR #38 で導入していただいた行番号はソートの意味がないのでソートできなくする変更も作っております。ご検討のほどよろしくお願いいたします。

テーブルのソート順を保持

---

src/main/java/logbook/bean/AppConfig.java
src/main/java/logbook/internal/gui/ConfigController.java
src/main/java/logbook/internal/gui/ItemController.java
src/main/java/logbook/internal/gui/RequireNdockController.java
src/main/java/logbook/internal/gui/ShipTablePane.java
src/main/java/logbook/internal/gui/Tools.java
src/main/resources/logbook/gui/config.fxml

お世話になっております。こちらは Issue #27 に関連して、一覧のテーブルの表示行数を稼ぐために、せっかくのサムネイルをオフにするのではなく、縮小するオプションを実装してみました。（パーセントで入力するだけなので拡大もできることになるので、文言は「拡大・縮小」としています。）ご検討のほどよろしくお願いいたします。

一覧における艦娘・装備画像の拡大・縮小オプション

---

src/main/java/logbook/internal/gui/ShipItem.java
src/main/java/logbook/internal/gui/Tools.java
src/main/resources/logbook/gui/require_ndock.fxml
src/main/resources/logbook/gui/ship_table.fxml

お世話になっております。先日の PR #38 に関連して、２つ問題を発見したので修正を作成してみました。ご検討のほどよろしくお願いします。
1. 列の表示・非表示を選択するとき、ラベルのないチェックボックスが表示される
#38 の実装時点では、行番号列のラベルは不要かなと思ってラベルを指定しなかったのですが、そのため列の表示・非表示のダイアログでも行番号列の選択用のチェックボックスがラベルのないチェックボックスとして表示されてしまっています。「行番号」という文字列を指定することで回避しています。
2. CSV出力がずれてしまう
行番号列はソートの影響を受けないという性格上 `ShipItem` の管理外の値になっているため、CSVには含まれませんが、CSVのタイトルはテーブルの `TableColumn` から生成されているためCSVに含まれ、結果として１行分ずれています。CSVに出力している時点で表計算ソフト側でも行番号は計算されていますし、CSVとして出力する必要がなさそうなので、タイトルから「行番号」列を抜くように変更しました。
ついでですが「exp」の列がCSVから抜けていたようなので追加しておきました。
もっとよい修正があればもちろんそちらのほうがよいので、その際は遠慮なくCloseしていただければと思います。よろしくお願いします。

艦娘一覧の行番号まわりの修正

---

src/main/java/logbook/internal/gui/ShipItem.java
src/main/java/logbook/internal/gui/ShipTablePane.java
src/main/resources/logbook/gui/ship_table.fxml

艦娘一覧で旧航海日誌にあってkaiにまだ未実装ないくつかの表示項目を実装するPRを作成してみました。既に実装済みの「対潜（素）」と同様、装備によるパラメータ変化を差し引いて素の値を出すようにしています。実装したパラメータは
- 火力
- 雷装
- 対空
- 装甲
- 回避
- 索敵
- 運
になります。また、 Issue #32 に経験値のNext値の表示要望がありましたのでこれも追加しています。ご検討のほどよろしくお願いいたします。

艦娘一覧の表示項目を増やす

---

src/main/java/logbook/internal/CheckUpdate.java
src/main/java/logbook/internal/CheckUpdateStartUp.java
src/main/java/logbook/internal/gui/MainController.java
src/main/resources/META-INF/services/logbook.plugin.lifecycle.StartUp
src/main/resources/logbook/gui/main.fxml

航海日誌を再起動することなく更新確認する機能が欲しくなったので[その他]から実行できるように

任意に更新確認する機能

---

src/main/java/logbook/api/ApiGetMemberNdock.java
src/main/java/logbook/internal/gui/FleetTabPane.java

艦娘を入渠させたときに、何か更新のトリガーがかかるまで航海日誌上の表示が変わらないので変わるようにする変更です。（`FleetTabPane.java`）
あともう一つはAPIの仕様上の問題ではありますが、入渠中の艦娘が修理完了（完了予定時刻１分前以降）の状態で入渠に移動すると、艦これ上では編成等で入渠表示だった艦娘が通常状態に戻りますが、航海日誌上は同様に更新されない上に所有艦娘等でもダメージ状態になったままなのを補正する変更です。（`ApiGetMemberNdock.java`）
ご検討いただけると嬉しいです。よろしくお願いします。

入渠ドックが更新されたとき艦娘の情報も更新

---

src/main/java/logbook/internal/log/BattleResultLogFormat.java

#112 にて、連合艦隊編成時に第三or第四艦隊で出撃したさい、NullPointExceptionがおきるバグがありましたので、パッチをPRします。

海戦・ドロップ報告書 書き込み時のバグ修正

---

src/main/java/logbook/internal/Ships.java
src/main/java/logbook/internal/gui/FleetTabShipPopup.java
src/main/resources/logbook/gui/fleet_tab_popup_rate.css
src/main/resources/logbook/gui/fleet_tab_popup_rate.fxml

12cm30連想噴進砲改二を装備した時に発動する対空噴進弾幕の発動率を艦隊ポップアップで表示します
加重対空値の式は[ここ](http://jbbs.shitaraba.net/bbs/read.cgi/netgame/13745/1439793270/205)を参照
[検証Wiki](http://ja.kancolle.wikia.com/wiki/%E8%88%AA%E7%A9%BA%E6%88%A6)の表現に倣って加重対空値の関数では丸めていません。
対空噴進弾幕の発動率の式は[ここ](http://ja.kancolle.wikia.com/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89:2471#5)を参照
[攻略Wiki](https://wikiwiki.jp/kancolle/%E8%88%AA%E7%A9%BA%E6%88%A6#AntiAircraft)では加重対空値を丸めたものとしているので対空噴進弾幕の発動率では加重対空値を、`int(加重対空値/2)*2`としています

対空噴進弾幕発動率を艦隊ポップアップで表示する

---

src/main/java/logbook/api/ApiReqKaisouSlotExchangeIndex.java

おそらく日進のスロット数を変更する仕様に伴って変更された `/kcapi/api_req_kaisou/slot_exchange_index` の構造に対応させました
Fixes #122

slot_exchange_indexの構造変更に対応

---

src/main/java/logbook/internal/gui/MainController.java
src/main/java/logbook/internal/gui/MainMenuController.java
src/main/resources/logbook/gui/main.fxml
src/main/resources/logbook/gui/main_menu.fxml
src/main/resources/logbook/gui/main_wide.fxml

#82 で追加した任意更新のメニューがメイン画面のスタイルをワイドにしていると存在しなかったので修正
main.fxmlとmain_wide.fxmlで重複しているのでメニューを別のファイルへ切り出して読み込む形に変更

メイン画面のメニューをスマートとワイドの両スタイルで共通の部品にする

---

src/main/resources/logbook/gui/main_wide.fxml

メイン画面をワイドにしている際、任務詳細を表示した時のScrollPaneが画面一杯まで広がらないので修正

ワイド時のScrollPaneの高さを修正

---

src/main/java/logbook/api/ApiGetMemberNdock.java

#93 の変更では入渠時間が更新されていないため、修復が完了した艦娘がお風呂に入りたい艦娘に表示されたままになるので修正

入渠ドックが更新された際にお風呂に入りたい艦娘に表示されないようにする

---

src/main/java/logbook/internal/gui/FleetTabPane.java
src/main/resources/logbook/gui/fleet_tab.fxml

最近実装された遠征には、遠征艦隊の火力などの合計がある一定値以上でないと成功しない場合があるので、艦隊タブで合計が見れると便利かと思い実装してみました。ご検討のほどよろしくお願いいたします。
↓こんな感じになります。

艦隊タブに火力・対空・対潜・索敵の合計を表示

---

src/main/java/logbook/internal/proxy/CaptureHolder.java

以前 Issue #158 として上げた問題の対応コードです。今でも `putRequest()` が複数回呼ばれる理由はわかっていませんが、以下のような修正を施した状態で３ヶ月程度問題なく動作したことを確認しています。ご検討のほどよろしくお願いいたします。

重複した request を追加しない

---

src/main/java/logbook/internal/Missions.java
src/main/java/logbook/internal/gui/MissionCheck.java
src/main/resources/logbook/mission/1/A5.json
src/main/resources/logbook/mission/1/A6.json
src/main/resources/logbook/mission/2/B5.json
src/main/resources/logbook/mission/4/D1.json
src/main/resources/logbook/mission/4/D2.json
src/main/resources/logbook/mission/5/E1.json
src/main/resources/logbook/mission/7/45.json

お世話になっております。
遠征が新規に実装され logbook-kai でまだ遠征条件が定義されていない場合に遠征条件確認のダイアログを開くと、[Missions.java:62](https://github.com/sanaehirotaka/logbook-kai/blob/master/src/main/java/logbook/internal/Missions.java#L62)でNPEが発生するようです。今後も新しい遠征が追加されると考えられるので、NPEの対応と未対応の遠征の場合には「？」のアイコンを表示するようにしてみました。
また、3月ごろに追加された遠征について遠征条件の定義を作成してみました。5月追加分（A5/A6）はまだ条件が不明なところも多いようなので作成していません。
ご検討のほどよろしくお願いします。

新規実装遠征への対応と遠征条件の一部追加

---

src/main/java/logbook/internal/Ships.java

- おそらく開発当時には索敵値がある装備がなかったため判定式の索敵係数に定義されていなかった slotitemtype を追加
- 拡張スロットの装備が索敵値の計算に反映されていなかったのを追加
Fixes #166
Fixes #167

判定式(33)周りの修正

---

src/main/java/logbook/internal/BattleLogs.java
src/main/java/logbook/internal/log/BattleResultLogFormat.java

海域・ドロップ報告書の CSV には海域名しか入っておらず略称（1-1等）が入っていないため、戦闘ログで表示するときに海域名の文字列から逆引きしているが、2020梅雨イベのE2(48-2)は海域名が南西諸島沖という1-2と全く同じ海域名を使用しているので、E2に出撃した記録が1-2として扱われている。
CSVのフォーマット変更（カラム追加）は困難なので、海域名のカラムに海域名だけではなく略称を頭につけるように変更。（例：南西諸島沖 -> 1-2 南西諸島沖）また、戦闘ログビューにて読み込む際には正規表現で `[0-9]+-[0-9]+` のパターンであるかをチェックし、そうであれば先頭の部分を略称として使用し、そうでなければ従来通りの処理を行うように変更。
Fixes #173 
既にE2に出撃済みの場合はそのデータに関しては「南西諸島沖」となっており1-2なのかE2なのかは判別不可能なので、20.6.1以前で記録されたE2の出撃データは正しく取れない。
※修正はこれで大丈夫だとは思いますが、私がまだE2にたどり着いておらず未確認なのと、既存のデータを壊したくないのでもう少しテストしてからマージします。

複数のマップで同一の海域名を持つ場合に対応 #173

---

src/main/java/logbook/api/ApiGetMemberShipDeck.java
src/main/java/logbook/api/ApiPortPort.java

#140 で報告にあるように、cond値が49未満の艦がいるのに疲労回復予定時刻が表示されない、または大きくずれた時間が表示されることがある。原因を調べたところ、問題となるのは出撃後に母港に帰投したとき、本来なら更新されるべき `AppCondition.condUpdateTime` が更新されず、結果として自然回復予想量が実際より多く計算されるため表示されなかったり実際より早い予想時刻が表示されたりする。
問題となっていたのは `ApiPortPort` で艦の cond 値が変化したかを調べている箇所で、Port での更新を反映する前と後で cond 値を調べているが、反映する前に cond 値が 49 以下だった艦のみチェックするようになっていた。その場合、以下の条件を満たしてしまうと cond 値の変化はなかった＝condUpdateTimeの更新はしないことになる。
- 出撃艦隊に属していない艦の中に cond  値が49未満の艦がいない（＝自然回復する艦がいない）
- 出撃艦隊に属している艦が帰投する直前、 cond 値が全艦50以上
- 帰投する直前の cond 値は最後に `ApiGetMemberShipDeck` で更新された値なので、帰投直前の戦闘を除いた最後の戦闘が終わり、進撃を選んだ直後の値になる。全艦49以上で出撃してS勝利をとると50以上となってこの条件を満たす。
- 帰投した後所属していた艦の中に（出撃で-15されることによって） cond 値が49未満の艦がいる
修正は単純に全ての艦について cond 値の変化をチェックするようにした。この場合自然回復以外にも出撃やcond値40未満の艦の入渠、演習等でも `condUpdateTime` …

cond 値自然回復検出ロジックを修正

---

src/main/java/logbook/api/ApiReqHenseiCombined.java
src/main/java/logbook/bean/BattleTypes.java
src/main/java/logbook/internal/gui/FleetTabPane.java
src/main/java/logbook/internal/gui/MissionPane.java
src/main/resources/META-INF/services/logbook.api.APIListenerSpi

- `/kcsapi/api_req_hensei/combined` の listener を登録し、連合艦隊の変更を即座に反映
- 遠征ペインにおいて連合艦隊編成時には第二艦隊を「未遠征」ではなく「（連合艦隊）」にして種別を表示
- 艦隊タブで連合艦隊編成時には第二艦隊を未遠征（青）ではなく第一艦隊同様の扱いに変更
- （将来第四の連合艦隊種別が出た時に「未結成」にならないように generic な名前を登録）

連合編成時に第二艦隊を未遠征扱いにしない

---

src/main/java/logbook/internal/BattleLogs.java
src/main/java/logbook/internal/gui/BattleLogController.java

#174 にて同じ海域名をもつ海域（1-2 及び 48-2）の CSV への記録方法を変更し、データ上は海域の区別が可能になったが、戦闘ログにおいて重複する現象が見受けられた。例えば同日に1-2に1回、48-2に1回出撃すると、それぞれ2回としてカウントされていた。原因は、対象期間内のすべての出撃ログに対し海域名でのマップを作成し、そのマップのエントリに対して該当するログをカウントしていたことによる。
- 海域名をキーにしてカウントするのではなく、短縮名（`1-2`など）でカウントするように変更

南西諸島沖両方(1-2, 48-2)に出撃した場合に両方の出撃としてカウントされるのを修正

---

src/main/java/logbook/internal/gui/BattleLogCollect.java
src/main/java/logbook/internal/gui/BattleLogController.java
src/main/java/logbook/internal/gui/BattleLogDetail.java

戦闘ログビューで同じ集計単位（ウィークリーなど）に同一海域名である1-2と48-2の両方の出撃記録があると、それらの海域を選択した時、右のテーブルで両方のデータが表示されてしまう。これも他の変更と同様、やはり海域名でフィルターしていたため。また、右下の集計ビューで海域を選んだ時はこれも海域名で集計していたため同一の海域とみなされてカウントされていた。
- 左の海域を選んだ時、海域短縮名でフィルターするように変更
- 右下の集計ビューでは短縮名+海域名を使うように変更

海域ごとの集計キーに短縮名を使用

---

src/main/java/logbook/internal/BattleLogs.java
src/main/java/logbook/internal/gui/BattleLogCollect.java
src/main/java/logbook/internal/gui/BattleLogController.java
src/main/java/logbook/internal/gui/BattleLogDetail.java
src/main/java/logbook/internal/gui/Tools.java
src/main/java/logbook/internal/gui/TreeTableTool.java

戦闘ログについて、右側のテーブルに関してはソート可能でカラム幅やソート順も記録されていたが、左側のツリービューに関してはそれらが実装されていなかったので実装を行なった。
具体的には、sort policy をセットして、各カラムのソート順に応じて適宜ソートを行うようにした。もともとカウントのカラムも文字列型になっていたため、数値に変更し数字でソートされるように変更した。また、カラム幅とソート順の記録を行うユーティリティークラスはなかったので、テーブル用のクラスを一部 abstraction/wrap してツリーの場合にも適用できるように変更した。記録内容はテーブルと同じマップに入る。カラムの show/hide については簡単ではないためまだ実装していない。
結果として以下のような仕様となる：
- 集計カラムでは海域短縮名（`1-2`など）の **数値で** ソートされる。つまり4-5の次は5-1であり、48-1ではなくなる。
- 集計カラムでのソートは集計単位以下で行われる。「デイリー」「ウィークリー」等はソートされない。
- それ以外のカラムでは回数の数値でソートされる。出撃カラムのみボス（`-`表示）は0としてソートされる。
- 戦闘ログを閉じた時のカラム幅とソート順（複数も可）が記録され、次に開いた時にその順に表示される。（リセットはできない。）
#165 の一部

戦闘ログの集計ビューをソート可能＆カラム幅・ソート順を記憶する

---

src/main/java/logbook/internal/gui/Deck.java
src/main/resources/logbook/gui/deck.fxml

- 艦隊リスト（左下）を選択したらその艦隊を表示するためスクロールするようにした
- 艦隊リストに艦隊を上下に並べ替えるボタンを配置
- 意味のないボタン（編成リストで最上位の編成を選んでいるときの↑ボタンなど）を disable するように変更
Fixes #145

編成記録ビューの改善

---

src/main/java/logbook/internal/SeaArea.java

画像から判明した札（９枚！）の更新を行う。同時に今後さらに増えてもいいようにidからenumに変換する時にswitch文ではなく`values`でループして探すように変更。実装者はもちろん実際につけてない札が多数なので動作確認はE2（沖縄方面舞台）までしかとっていないので間違い等あるかもしれないがそれは後日対応する。現状登録した札は以下：
- 千島方面部隊
- 沖縄方面部隊
- 第二遊撃部隊
- 小笠原方面部隊
- 南東方面部隊
- 第二艦隊
- 前進部隊
- 機動部隊前衛
- 機動部隊

夏イベ2020後段作戦用の札を追加

---

src/main/java/logbook/internal/gui/MissionPane.java

艦これの仕様上残り1分から遠征帰投可能なので、5分ではなく1分から濃い黄色に変わるように変更する。
Fixes #134

遠征プログレスバーが濃い黄色になる時間を1分に変更 #134

---

src/main/java/logbook/bean/AppConfig.java
src/main/java/logbook/internal/gui/ConfigController.java
src/main/java/logbook/internal/gui/FleetTabPane.java
src/main/java/logbook/internal/gui/MainController.java
src/main/resources/logbook/gui/config.fxml

艦隊タブの色のストラテジーを変更し、かつユーザーによる設定を可能にした。現状のタブの色は：
- 大破艦あり：赤
- 中破艦あり：オレンジ
- 未補給の艦がいる場合：黄色
- 第二艦隊以降で遠征や連合艦隊編成に含まれていない場合：青
の順番に評価され、上位の条件に適合した場合にその色が決まる。色が決まった場合は左上から右下にかけてグラデーションでタブの色を変えている。
これを以下のように変更する。まず以下の順に評価し、
- 大破艦あり：赤
- 中破艦あり：オレンジ
- 小破艦あり：黄色
- 小破未満のダメージ艦あり：水色
- 全艦無傷：なし
タブの左上の色を決定する。次に
- 未補給の艦がいる：黄色
- 第二艦隊以降で遠征や連合艦隊編成に含まれていない：青
によってタブの右下の色を決定する。それぞれの色が決定したらその色に従って左上から右下にかけてグラデーションで表現する。どちらかの色がない場合は背景色、両方の色がない場合は色なしのタブになる。
また、これらの色の設定を設定可能にした。ただデフォルトの挙動は従来と近いものにするため、指定しない（空欄）場合はおおむね上のような色設定になるようにしている。なので指定なし（その条件でも色を変えない）にしたい場合はハイフン（`-`)を受け付けることにした。設定画面にもそのような注釈をつけている。
ついでにタブに色がついたときにタブの縁取りがなくなっていたのも修正した。
Fixes  #136

艦隊タブの色を設定可能にする

---

src/main/java/logbook/api/ApiReqPracticeBattle.java
src/main/java/logbook/api/ApiReqPracticeBattleresult.java
src/main/java/logbook/api/ApiReqPracticeMidnightBattle.java
src/main/java/logbook/bean/AppCondition.java
src/main/java/logbook/internal/Ships.java
src/main/java/logbook/internal/gui/BattleDetail.java
src/main/java/logbook/internal/gui/MainMenuController.java
src/main/resources/META-INF/services/logbook.api.APIListenerSpi
src/main/resources/logbook/gui/battle_detail.fxml
src/main/resources/logbook/gui/main_menu.fxml

これまで「現在の戦闘」で詳細が確認できていたのは通常の戦闘のみで、演習については確認できていなかった。データとしては通常の戦闘と同様なのでルート情報等演習にない項目を除けばそれほど修正量は多くないので、まずこのPRでは直近の演習のデータを通常の戦闘とは別に `AppCondition` に保持し、それを表示する別メニューを実装した。ただし通常の戦闘とは異なり戦闘ログ（CSV）も戦闘詳細（JSON）も保存されていないので、このPRではあくまでも直近の演習のデータのみの対応となっている。
CSVや詳細についてはこの後 #92 の対応等で実装を行うかもしれないが、とりあえず現時点では直近の演習のみの対応とする。
Fixes #73

演習詳細を出せるようにする #73

---

src/main/java/logbook/bean/AppConfig.java
src/main/java/logbook/internal/gui/ConfigController.java
src/main/java/logbook/internal/gui/Tools.java
src/main/resources/logbook/gui/config.fxml

ギミック達成等で表示されるトーストの表示位置を変更できるようにした。変更内容は：
- 設定画面に「トーストの位置」という新たな項目を設置し、「左上」「左下」「右上」「右下」から選べるようにした
- デフォルトの表示位置はこれまで同様の位置である「右下」とした
- 設定を変更したらお試しのトーストを表示するようにした
また、コードを調査してたら、設定で「通知でトーストを表示」の設定が有効なのは遠征・入渠の通知のみだったので、その設定は遠征・入渠用だとわかるように位置を遠征・入渠用の項目の右に移動し、その空いた行に新たな設定を配置した。
Fixes #97

トーストの表示位置を設定可能にする #97

---

src/main/java/logbook/api/ApiReqPracticeBattle.java
src/main/java/logbook/bean/BattleLog.java
src/main/java/logbook/bean/Chara.java
src/main/java/logbook/bean/Enemy.java
src/main/java/logbook/internal/ShipImage.java
src/main/java/logbook/internal/Ships.java
src/main/java/logbook/internal/gui/BattleDetail.java

#187 にて演習においても戦闘詳細と同等の情報を表示するようにしたが、演習相手の情報が敵艦と同様に扱われていたため、以下のような挙動になっていた。
- 中破以上してもダメージ絵にならない
- HPが0いかになると撃沈表示となり轟沈したかのように見える
この挙動を実際の演習と合わせるため、中破絵の表示および大破どまりにするように変更した。ただHP1残しと撃破が区別できないと困るので、数値での表記は1にせずに0やマイナス表示のままとする。
N/A

演習詳細で相手艦の中破以上をダメージ絵で表示し、かつ撃破した相手艦を撃沈表示にしない

---

src/main/java/logbook/internal/gui/FleetTabPane.java

https://github.com/sanaehirotaka/logbook-kai/issues/192#issuecomment-658583746 でご指摘のあったとおり、本来無傷用の設定を参照すべきところで誤って大破用の設定を参照していたことによる。
`getTabColorNoDamage()` を呼ぶように修正。
Fixes #192

無傷時に大破時の色を使っていたバグを修正 #192

---

src/main/java/logbook/bean/AppQuest.java
src/main/java/logbook/bean/AppQuestCollection.java
src/main/java/logbook/internal/gui/MainController.java
src/main/java/logbook/internal/gui/QuestPane.java
src/main/resources/logbook/gui/main.css

任務の進捗をチェックするときなど、受諾中以外の任務が見れたほうがよい場合がある。これに対応するため受諾中でない任務も薄くして表示するようにした。
主にチェックしたいのは受諾中の任務だと思うので、ソート順は変わらずID順だが、受諾中の任務を上位に持ってくるようなソート順にしている。
また、昔は任務を開いたときにその開かれているページにある任務の情報のみが送られてきていたため、これまでに取得した任務の情報を保持しておく必要があったが、任務にフィルター（カテゴリごとの絞り込み）が実装されたとき以降は任務を開いたときにすべての任務情報が送られてくるように変更された。その対応コードも同時に実装しておく。
Fixes #141

受諾中でない任務も表示する #141

---

src/main/java/logbook/api/ApiGetMemberQuestlist.java
src/main/java/logbook/bean/AppQuestCollection.java

`20.7.5` で受諾していない任務を表示する変更を入れたが、同時に今の任務のAPIは全てのページのデータが送られて来るため常にリストを置き換えるように変更したところ、 #194 の報告にあるような不具合が発生した。原因は任務画面の縦のタブ（左側にあるデイリー等で絞り込むタブ）をクリックした時にも任務APIが呼ばれ、その場合はそのタブに属する任務の情報しか送られてこないため。横のタブ（上側にあるカテゴリで絞り込むタブ）のほうは任務APIは呼ばれないため問題の不具合は生じない。
どのタブをクリックした時に呼ばれた任務APIなのかはリクエストからわかるので、tab index が0、つまりAllの時のみリストの置き換えとし、それ以外の場合は以前のようにデータが来た任務についてのみ更新するように変更した。技術的には恐らくAllのときのみ対応すればいいはずだが、将来任務APIの仕様が変わってAllのタブが0以外になったりする場合なども考慮し、上記のような実装を採用した。（ちなみに置き換えを採用している理由は、以前の実装だと過去に一度でも受けたワンオフ任務などをlogbook-kaiを通さずにクリアしてしまうと削除を押すまで永遠に残り続けてしまうため。）
Fixes #194

任務でAllのタブの場合にのみデータを更新する #194

---

src/main/java/logbook/bean/MissionCondition.java
src/main/java/logbook/bean/TestAllPredicate.java
src/main/resources/logbook/mission/1/A4.json

A4の遠征条件が現状判明している条件と異なっている。
A4の遠征条件の定義ファイルを更新。
関連して、遠征条件の評価の logical operator （and/or）は `Predicate` で実装されているが、and 条件なら片方の条件が false の時点で、or 条件なら true の時点で探索を終了してしまうため、結果としてもう片方の条件が評価されない。そうなると遠征条件ビューにおいては最初に満たしていない条件が出てきた時点でそれ以降の条件を満たしているかどうかがわからず、「？」で表示されてしまう。それを解決するため、評価を行う際には operator の双方の値の評価を行ってから戻り値を計算するように変更した。
（従来バージョンだと火力条件を満たしていない時点で、対空以降の条件はすべて「？」で表示される。）
#197 (一部)

遠征条件の修正および遠征条件ビューの改善

---

src/main/java/logbook/bean/AppItemTableConfig.java
src/main/java/logbook/bean/AppShipTableConfig.java
src/main/java/logbook/bean/ParameterFilterConfig.java
src/main/java/logbook/internal/ComparableFilter.java
src/main/java/logbook/internal/gui/ItemAirBaseController.java
src/main/java/logbook/internal/gui/ItemController.java
src/main/java/logbook/internal/gui/ItemItemController.java
src/main/java/logbook/internal/gui/ParameterFilterPane.java
src/main/java/logbook/internal/gui/ShipTablePane.java
src/main/resources/logbook/gui/item.fxml
src/main/resources/logbook/gui/item_airbase.fxml
src/main/resources/logbook/gui/item_item.fxml
src/main/resources/logbook/gui/param_filter_pane.fxml
src/main/resources/logbook/gui/ship_table.fxml

所有艦娘および所有装備（装備一覧および基地航空隊）においては、装備一覧以外はフィルターがいくつか用意されていたが、事前に定義されたパラメータのみでしかフィルターできなかった。それをフィルターしたいパラメータを選択可能にし、それを複数組み合わせてフィルターできるように変更した。かつ、今までそれらのフィルターがなかった装備一覧にもフィルターを導入した。
Fixes #83

各種ビューで任意の（整数値の）パラメータでフィルターできるようにする

---

src/main/resources/logbook/mission/7/44.json

44の遠征条件が正しくない。条件は「全6隻。空母(水母,護母可)1隻、水母1隻、軽1隻、(駆+海防)2隻、他1隻必要」だが、 logbook-kai での定義は「空母2隻、水母1隻、軽1隻、(駆+海防)2隻」となっていた。
既存の条件の空母を1に減らして水母を追加するだけだと条件式の評価の実装上（艦隊の艦を最初からチェックし、条件に合致した艦を除いていく手法）うまくいかないので、式を二つ「空母1隻、水母1隻、軽1隻、(駆+海防)2隻、他1隻」か「水母2隻、軽1隻、(駆+海防)2隻、他1隻」とした。
Fixes #204

44の遠征条件の修正 #204

---

src/main/java/logbook/internal/gui/FleetTabShipPane.java
src/main/resources/logbook/gui/main.css
src/main/resources/logbook/gui/ship.css

cond 値の変化がより視覚的にわかるように変更を行った。30-52以外の cond 値の場合は太字にし、かつ文字の背景に色を付けて視認しやすいようにした。
統一感を持たせるため以下のルールにした。
- 状態分けは従来通り 0-19, 20-29, 30-49, 50-52, 53-100
- 二段キラ(53以上)と疲労(29以下)は通常状態とは違うということでboldにし、背景色をつける
- 背景色は文字色と同じでアルファ(透明度)0.1で調整する
またHPが満タンの場合にHPの表示を青で表示するようにした。
Fixes #198

cond値の表示色を改善する

---

src/main/java/logbook/internal/ShipImage.java

経験値・HPゲージの背景色がグレーで見難いという声を受けて、ツイッターで背景を白にするアンケートを取ってみたところ、現状維持が 53%、白抜きが47%となり、ほぼ拮抗した。現状維持の意見は色の感じが現状のままのほうがよい（目立ちすぎない）という意見で、白抜きが良いという意見はゲージの量が見難いという意見だと考えられ、かつリプライで見難いのは色のせいではなく背景が透けているせいではないかという意見もあった。実際に調査してみると、背景色は実際すでに白で、アルファが0.6（40%透ける）だったことがわかった。背景色は特にグラデーションもしていないが、実際の印象は右に行くほどグレーが濃くなっているように見える。その理由は背景になっている艦娘バナー画像が
のように右下に黒い線が入っており、ちょうどそこに透明度がある程度高い背景色が重なるためなせいなこともわかった。
そこで背景色のアルファを0.6から0.9に変更した（同時に白で0.9だとかなり強く見えるので少し色を落とした）。また、経験値が max、レベル99または175の艦については経験値ゲージは表示しないようにした。
Fixes #200

経験値・HPゲージの背景の透明度を落とす #200

---

src/main/java/logbook/internal/CheckUpdate.java
src/main/resources/logbook/update/update.js

Java11 のパッケージ配布方法はまだ未定ではあるが（ #208 など）、次のバージョンのリリースまでには Java 11 版の自動更新に対応しておく必要があるため（でないと次のバージョンを配布するときにまた手動になる）、スクリプトを更新しておく。本体側で利用している Java のバージョンを調べ、`11` だったら -java11 を利用するようにする。（現時点ではまだベータなのでJava 12以降は想定していない。）
また、開発用途として `logbook.use.prerelease=true` をセットして起動した場合は Prerelease のものでも自動更新するようにする。
いずれの場合も本体側でこれらの条件を調べ、スクリプトには `-D` で渡すように実装している。

Java11 で起動した場合 -java11 のパッケージをダウンロードする

---

src/main/java/logbook/internal/Ships.java
src/main/java/logbook/internal/gui/ShipItem.java
src/main/resources/logbook/supplemental/ships.json

所有艦娘ビューでは各種パラメータの素の値を計算するのに、（現状の値）-（装備の値の合計）で計算していたが、（そこそこ前の）艦これの仕様変更で装備する艦によってパラメータの増減が起こるようになり、この計算式では正確に素の値を計算できなくなった。これらのパラメータの増減値は API では取れていない模様（UIに表示されているので何らかの手段はありそうに思えるが）。
艦娘の素の値は、パラメータの種類によって大きく２通りに分けられる：
- 火力・雷装・対空・装甲・運：艦娘ごとに定義されている最低値＋近代化改修値
- 対潜・回避・索敵：艦種・レベルによる変動値＋近代化改修値（対潜のみ）
前者はどちらもAPIから取得可能なので、計算方法を変更する。後者の値は以下の式から求められるが：
```
((Lv99時の値) - (Lv1時の値)) * Lv / 99 + (Lv1時の値)
```
Lv99時の値は API から取得可能だが、Lv1時の値は取得できない。ドロップ時などLv1の状態の艦を獲得したときに記録することも考えられるが、全装備を解除したときにのみ記憶できることと、そもそも改修後の艦のLv1の値は計算で導くしかなく、あまり現実的ではない。そこでこれら３種類のパラメータについては Lv1 時の値をデータとして持つことで対応することにした。将来新艦が実装されたときにはこの定義がないことになるが、その場合は従来通りの計算方法で計算するので増減分の少しのズレが生じることになる。完璧な解ではないが多くのケースで正しい値が計算できるのでこの方法を採用する。
なお、本日時点（2020/07/22）で夏イベ2020で実装された艦の中で改装後のLv1の値がまだwikiなどに書かれていない艦が存在する。これらの艦は未対応とする。
Fixes #201

素の値を修正 #201

---

src/main/java/logbook/internal/gui/ParameterFilterPane.java
src/main/java/logbook/internal/gui/ShipTablePane.java
src/main/resources/logbook/gui/param_filter_pane.fxml

`ParameterFiterPane` の save/load で `type` についての処理がごっそり抜けおちているため。艦娘一覧、装備一覧（装備・基地航空隊）全てにおいて再現を確認。
Save/Load のコードを追加。また、数値型ではあるが Choice で実装されているカラムが選択されていた場合、 toggle をオフにしている時にでも enabled な状態で load されていたのを修正。同時に空のセルの背景に色がつく場合があったのを修正。
Fixes #210

パラメータフィルターの型を保存と細かな修正 #210

---

src/main/java/logbook/internal/gui/ShipItem.java

所有艦娘ビューでの素の値の計算部分でコピペミスにより対空・装甲・運の値が全部対空にセットされていて結果的に対空は運の値、装甲・運は古い計算方法（現在の値-装備による増分）で計算するようになっていた。
正しい項目にセットするように修正。また確認中に定義上の対空値を `api_taik` （耐久）を参照していたことも判明したので正しいもの（`api_tyku`）に修正。
Fixes #217

艦娘の素の値の計算間違いを修正 #217

---

src/main/java/logbook/bean/AppConfig.java
src/main/java/logbook/bean/AppItemTableConfig.java
src/main/java/logbook/bean/AppShipTableConfig.java
src/main/java/logbook/internal/gui/AirBaseController.java
src/main/java/logbook/internal/gui/AirBaseItem.java
src/main/java/logbook/internal/gui/ConfigController.java
src/main/java/logbook/internal/gui/DeckBuilder.java
src/main/java/logbook/internal/gui/ItemAirBaseController.java
src/main/java/logbook/internal/gui/ShipController.java
src/main/java/logbook/internal/gui/ShipTablePane.java
src/main/resources/logbook/gui/airbase.fxml
src/main/resources/logbook/gui/config.fxml
src/main/resources/logbook/gui/item_airbase.fxml
src/main/resources/logbook/gui/ship_table.fxml

デッキビルダー形式の出力サポートを行った。デッキビルダーは基本的に艦隊所属艦の情報のみを必要とするため、所有艦娘のビューで表示されている艦のうち何れかの艦隊に所属している艦の情報を（その艦隊中の位置で）出力するように実装した。メニューは２つ：
1. 表示されている艦隊所属艦をクリップボードにコピー
1. 選択した艦隊所属艦のみクリップボードにコピー
1のほうは現在そのタブに表示されてる全ての艦娘のうち艦隊に所属している艦娘を、2のほうはそのテーブルにおいて選択されている艦娘のうち艦隊に所属している艦娘をデータに含めるようにした。つまり、全艦娘のタブで1を選択してデータを生成すれば、現状の第一艦隊から第四艦隊までの全てのデータが生成される。特定の艦隊のみ生成したい場合はそれらの艦隊に属する艦娘のみを選択して2を実行すればよい。
関連して、例えば連合艦隊時に第一艦隊と第二艦隊だけデータを生成したい場合があるのを想定し、艦隊所属艦のみを表示できるタブを用意した。設定から「所有艦娘一覧に全艦隊のタブを追加」を選択すれば表示されるようになる。このタブを利用して第一艦隊と第二艦隊に所属している艦娘を選択し、2を実行すれば第二艦隊までの情報が生成される。
また、[艦隊分析](https://kancolle-fleetanalysis.firebaseapp.com/#/)さんへの艦娘データ入力をサポートした。こちらは全艦娘のデータが必要なので、（テーブル上での選択等は関係なく）すべてのロックされている艦娘のデータをクリップボードにコピー可能とした。
所有艦娘のビューで前回開いていたタブの情報が記憶されていなかったので記憶するように変更した。また、所有装備の基地航空隊タブで同一装備・同一属性（改修値・熟練度）でグルーピングしないオプションも同時に実装した。 …

デッキビルダー形式の出力サポートと関連する変更

---

src/main/java/logbook/bean/ShipMst.java
src/main/java/logbook/internal/gui/ShipController.java

所有艦娘一覧の全員タブのソート順はこれまでレベルの降順、艦種IDの昇順なので実質レベルソートとほぼ同じ挙動になっていたが、艦これ本体の艦種ソート順と同じソート順は実現できていなかったので、全員タブのデフォルトソート順を艦これの艦種ソートと同じにする。

所有艦娘一覧の全員タブのソート順を艦これの艦種ソートに合わせる

---

src/main/java/logbook/internal/gui/InternalFXMLLoader.java
src/main/java/logbook/internal/gui/Main.java
src/main/java/logbook/internal/gui/MainMenuController.java
src/main/java/logbook/internal/gui/Tools.java

演習詳細も戦闘詳細のように表示できるようにしているが、同じクラスを使っているためウィンドウの位置・サイズは同一の情報となっているので #214 に示されたような挙動となっている。
FXML をロードするときに、クラス名がキーとなっているところに副キーを指定できるように変更し、既に戦闘詳細用で保持している情報を壊さないように演習詳細時にのみ副キーを指定して別に記憶できるようにした。
#214

同じクラスのウィンドウ位置・サイズを複数記憶する #214

---

src/main/java/logbook/internal/gui/Tools.java

`logbook.internal.gui.Tools.Windows.{defaultCloseAction,defaultOpenAction}` を利用しているプラグインが軒並み動作しなくなるのでパラメータを持たない関数を用意

プラグインの後方互換

---

src/main/java/logbook/bean/BattleTypes.java
src/main/java/logbook/internal/PhaseState.java

Colorado特殊攻撃、僚艦夜戦突撃が発動しても、「通常攻撃」として表示される。これは単に陸奥タッチ実装以後のIDに対応していないため。しかし #226 にあるように、連合艦隊で僚艦夜戦突撃が発動した場合なぜか第一艦隊の旗艦が攻撃したことになっている。これは `at_list` にある番号がなぜか0（第二の旗艦なら本来は6）で送られてきているため。おそらく艦これのバグと思われる（そもそも艦これ本体でも第一艦隊によるカットインが表示されるバグがあり、それが直された経緯があるが、その際に恐らくクライアント側で対応したと考えられる）。
まず新しい特殊攻撃については定義を追加する。上記の艦これのバグについては、将来修正されることも考えられるので、まず index が 0 でかつ連合艦隊である場合にのみこちら側で補正するようにした。
#226

Colorado特殊攻撃、僚艦夜戦突撃に対応 #226

---

src/main/java/logbook/api/ApiReqMapNext.java
src/main/java/logbook/api/ApiReqMapStart.java
src/main/java/logbook/bean/AppConfig.java
src/main/java/logbook/bean/DeckPort.java
src/main/java/logbook/internal/gui/ConfigController.java
src/main/resources/logbook/gui/config.fxml

今のところの艦これの挙動において、連合艦隊時に第二艦隊の旗艦が大破しても以降の進撃で轟沈することはないと考えられている。なので logbook-kai における大破進撃警告が実際にはあまり意味をなさず、逆に第二艦隊の旗艦以外も大破している場合に警告を無視してしまうリスクもあるため警告を抑制するオプションには意味があると考えられ、そのように実装を行なった。ただしこれは明確に宣言されている仕様ではないためいつ変更されるか不明なため、デフォルトは第二艦隊の旗艦であっても大破警告を行うほうにしておく。
#227

第二艦隊の旗艦の大破警告を抑制するオプション #227

---

src/main/java/logbook/bean/MissionCondition.java
src/main/java/logbook/internal/ImageListener.java
src/main/java/logbook/internal/Ships.java
src/main/java/logbook/internal/gui/ShipController.java
src/main/resources/logbook/mission/7/44.json

#225 の報告によれば、搭載数0のスロットに艦載機を搭載した場合、遠征時の成功条件の対潜値の計算には含まれないとのこと。現状は単純に艦娘のステータス値（艦これ本体で表示される値と同じ）であるため、その場合 over estimate となり成功条件を誤る可能性がある。本来なら搭載数0の場合正味のステータス値が変化すべきであるが、現状の艦これの仕様はそうなっている模様。
対潜値の計算は複雑な計算式があると考えられ、そのまま厳密な計算式を実装することはメンテナンスコストの意味でも現実的でない。なので遠征の場合は under estimate 側に振った方がよい（過剰に装備を搭載することになるだけなので）ので、艦娘の素の対潜値に加えて装備の対潜値を加えることで対潜値の計算を行うようにする。火力等ほかのパラメータも同様に搭載数0の場合加算されないのかもしれないが、対潜値以外については今後の検証を待つ。
#225

遠征条件の対潜値計算方法の変更

---

src/main/resources/logbook/quest/854.json

Z前段作戦(854)の進捗カウントにおいて、S勝利だとカウントされないという現象が起きた。確認したところ本来「SまたはA」と指定すべきところが「A」のみの指定になっているためだった。
SまたはAに変更。報告があった2-4だけでなく、6-1、6-3も同様だった。6-1で問題の再現および修正の確認を行った。
#232

Z前段作戦の条件を修正 #232

---

README.md
src/main/java/logbook/internal/CheckUpdate.java
src/main/java/logbook/internal/gui/VersionController.java
src/main/resources/logbook/update/update.js

メインの開発を引き継いで３ヶ月程度経過し、期間限定イベントの時期も無事超えることができたため、開発リポジトリをオリジナルの sanaehirotaka さんのところから @Sdk0815 の fork へと変更する。この PR では
- 自動更新の差し先を変更
- バージョン情報のリンクの差し先を変更
- README.md の先頭に変更告知を記載
の変更をカバーする。最新の `v20.9.1` は当然元のリポジトリを差しているため次のバージョンは以前と同様にこちらに公開する必要があるが、その `v20.9.2` が指す先は Sdk0815 のものを指すためその次のバージョンからはそちらにだけ公開すればよいはず。`v20.9.2` をリリースした後に残りに種々のリンク先の変更等を行なって完了とする。
N/A

リポジトリ変更に備えて自動更新等のURL変更及び告知
